### ISSUE TITLE
Did the paper report the accuracy of validation/test sets on Twitter dataset?

### ISSUE THREAD

**Issue by thcheung** [xiaolan98/BDANN-IJCNN2020#1]
https://github.com/xiaolan98/BDANN-IJCNN2020/blob/d7d59c7742bcf3f82d378eb359e1e27f0f73721b/src/process_twitter.py#L287

In the above line, you use the validation directory to form the test_data.

When I changed it to the test directory, I got a very poor conformance, like 50% accuracy. Did the paper report the accuracy of validation/test sets on Twitter dataset?

**Comment by xiaolan98** [comment]
No. There are just the training and testing data. The “validate” here is the test set for the Twitter set. I just follow the setting of previous work (EANN and MVAE).

**Comment by thcheung** [comment]
Got it. Thank you for your response.
