### ISSUE TITLE
Question about experiments with comparision models in your paper(BDANN)？

### ISSUE THREAD

**Issue by JieCaoSec** [xiaolan98/BDANN-IJCNN2020#3]
First of all, thank you very much for sharing your work on BDANN. After reading your paper, I found that the EANN and MVAE models are not well reproduced, and many multimodal fake news detection works use them as benchmarks. Could you please share the code for these two control experiments, thank you very much again.

**Comment by xiaolan98** [comment]
Hi, I didn't reproduce the MVAE model, I use the results reported in the original paper. But I reproduce the EANN based on their original code, especially for the Twitter dataset. Will release the code later.
