### ISSUE TITLE
facing an error in line 144 read_post function 

### ISSUE THREAD

**Issue by sahartahmasebi** [xiaolan98/BDANN-IJCNN2020#4]
Hi. thank you for sharing your code. I'm trying to run BDANN_twitter.py but it faces an error line 144, in read_post
    texts = open(pre_path + 'train_posts.txt', 'r').readlines()
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6314: character maps to <undefined>. could you tell me what changes is needed to get rid of this error?

**Comment by xiaolan98** [comment]
Hi, thanks for your interest. I guess you can change code texts = open(pre_path + 'train_posts.txt', 'r').readlines() to texts = open(pre_path + 'train_posts.txt', 'r', encoding="utf8").readlines()

Hope this helps you.
